export const CALENDAR_CARDS_CREATED = 'CALENDAR_CARDS_CREATED';
export const ALLOCATION_DETAIL_ADDED = 'ALLOCATION_DETAIL_ADDED';
export const ALLOCATION_DETAIL_SAVED = 'ALLOCATION_DETAIL_SAVED';
export const CALENDAR_DAY_SELECTED = 'CALENDAR_DAY_SELECTED';
export const PAST_DAYS_LOADED = 'PAST_DAYS_LOADED';
export const FUTURE_DAYS_LOADED = 'FUTURE_DAYS_LOADED';
export const CALENDAR_DAYS_LOADED = 'CALENDAR_DAYS_LOADED';
export const CALENDAR_MONTH_NAVIGATED = 'CALENDAR_MONTH_NAVIGATED';
